//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.09 at 09:27:37 PM MESZ 
//


package generated_laura;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Rezeptname"/>
 *         &lt;element ref="{}Anmerkungen"/>
 *         &lt;element ref="{}Zutaten"/>
 *         &lt;element ref="{}Zubereitung"/>
 *         &lt;element ref="{}Brennwert"/>
 *         &lt;element ref="{}Kommentare"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}id_rezept use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rezeptname",
    "anmerkungen",
    "zutaten",
    "zubereitung",
    "brennwert",
    "kommentare"
})
@XmlRootElement(name = "Rezept")
public class Rezept {

    @XmlElement(name = "Rezeptname", required = true)
    protected String rezeptname;
    @XmlElement(name = "Anmerkungen", required = true)
    protected String anmerkungen;
    @XmlElement(name = "Zutaten", required = true)
    protected Zutaten zutaten;
    @XmlElement(name = "Zubereitung", required = true)
    protected Zubereitung zubereitung;
    @XmlElement(name = "Brennwert", required = true)
    protected String brennwert;
    @XmlElement(name = "Kommentare", required = true)
    protected Kommentare kommentare;
    @XmlAttribute(name = "id_rezept", required = true)
    protected BigInteger idRezept;

    /**
     * Gets the value of the rezeptname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRezeptname() {
        return rezeptname;
    }

    /**
     * Sets the value of the rezeptname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRezeptname(String value) {
        this.rezeptname = value;
    }

    /**
     * Gets the value of the anmerkungen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnmerkungen() {
        return anmerkungen;
    }

    /**
     * Sets the value of the anmerkungen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnmerkungen(String value) {
        this.anmerkungen = value;
    }

    /**
     * Gets the value of the zutaten property.
     * 
     * @return
     *     possible object is
     *     {@link Zutaten }
     *     
     */
    public Zutaten getZutaten() {
        return zutaten;
    }

    /**
     * Sets the value of the zutaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zutaten }
     *     
     */
    public void setZutaten(Zutaten value) {
        this.zutaten = value;
    }

    /**
     * Gets the value of the zubereitung property.
     * 
     * @return
     *     possible object is
     *     {@link Zubereitung }
     *     
     */
    public Zubereitung getZubereitung() {
        return zubereitung;
    }

    /**
     * Sets the value of the zubereitung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Zubereitung }
     *     
     */
    public void setZubereitung(Zubereitung value) {
        this.zubereitung = value;
    }

    /**
     * Gets the value of the brennwert property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrennwert() {
        return brennwert;
    }

    /**
     * Sets the value of the brennwert property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrennwert(String value) {
        this.brennwert = value;
    }

    /**
     * Gets the value of the kommentare property.
     * 
     * @return
     *     possible object is
     *     {@link Kommentare }
     *     
     */
    public Kommentare getKommentare() {
        return kommentare;
    }

    /**
     * Sets the value of the kommentare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Kommentare }
     *     
     */
    public void setKommentare(Kommentare value) {
        this.kommentare = value;
    }

    /**
     * Gets the value of the idRezept property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIdRezept() {
        return idRezept;
    }

    /**
     * Sets the value of the idRezept property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIdRezept(BigInteger value) {
        this.idRezept = value;
    }

}
